namespace DbScaffold.Models
{
    public enum ServerPackets : int
    {
        SWelcomeMessage = 1,
        SIngame,
        SPlayerData,
        SPlayerMoove,
        SPlayerAttack,
        SPlayerAttach,
        SDisconnect,
        SClosedConnectionForClient,
        SCRefused,
        SInWorld,
        SSelect,
        SCSelected,
        SCInstantiatePlayer,
        SQuestItemCollected,
        SRaceInformation,
        SCharacterCreated,
        SCHungerUpdated,
        SInitializeConnection,
        SNpcDialogData,
        WTElapsed,
        CLoginRequest,
        CSrptConfirmHandshake,
        CCSalt,
        CCSrpSession,
        CSAbilitySelected,
        SPMoveIndicator,
        SCCSelected,
        SReadBook,
        OpenBook,
        SUpdateHealth,
        SUpdateFatigue,
        SAbilityMoving,
        SAbilityCollission,
        SCBlockActive,
        SCBInactive,
        SAbilityExpired,
        SCUiUpdate,
        CIncomingMessage,
        ItemEquiped,
        TradingUiRequestApproved,
        SSummon,
        SSeasonChange,
        SAbilityCombo,
        OnTeleportTriggerEnter,
        OnTeleportTriggerExit,
        TickDamageApplied,
        OnPlayerDisorientated,
        SCSpeedUpdated,
        SCharacterMounting,
        SCharacterMounted,
        SCDismounted,
        SnpcMoveToPoint,
        PlayerAiming,
        PlayerAimingEnding,
        SNpcInit,
        SActivateAbility,
        NpcMoving,
        NpcStopped,
        AbilityCollided,
        NpcPlayAttackAnimation,
        NpcFirePref,
        PlayerHit,
        CQEnabled,
        CQDisabled,
        SAbilityCollissionNpc,
        ZNotifyItemPicked,
        CItemRespawned,
        InitAbilitInWorld,
        GenerateReadingLine,
        ActivateQuizPart,
        QuestCompleated,
        QuestAccepted,
        WeaponPartsRecived,
        ActivateShopWeapon,
        LoadTrairMenu
    }

    public enum ClientPackets : int
    {
        CThankYouMessage = 1,
        CMovement,
        CAttacking,
        CAttach,
        CDisconnect,
        CConnect,
        CInWorld,
        SCSelect,
        SCInitPlayer,
        SCSelected,
        CQICollected,
        CRSelected,
        CANewCharacter,
        CCHungerUpdate,
        CNPCSI,
        CSrpHandShake,
        CSendLoginRequest,
        CSrpVerifier,
        QGetDialog,
        CSAbilitySelected,
        PHIMovement,
        PHIMovementInit,
        CCSelected,
        CGetBook,
        COpenBook,
        ProjectileHit,
        SCBlockActive,
        SCBInactive,
        IcomingChatMsg,
        TradingUiRequest,
        CombatComboGetNext,
        OnTeleportTriggerEnter,
        OnTickingDamageTriggerEnter,
        OnStunTriggerEnter,
        OnSlowTriggerEnter,
        OnTeleportTriggerExit,
        OnTickingDmgActive,
        OnDisorientation,
        SCSpeedUpdated,
        SCharacterMounting,
        SCDismounted,
        CharacterAiming,
        CharacterAimingEnd,
        NpcSigned,
        NpcMoving,
        AbilityExpired,
        MoveAbility,
        NpcStopped,
        AbilityCollided,
        NpcPlayAttackAnimation,
        SNpcFirePref,
        SCharacterHit,
        CQEnabled,
        CQDisabled,
        ProjectileHitNpc,
        CItemRespawn,
        NotifyNewAbility,
        BoundAbilitySelected,
        GenerateReadingLine,
        QReadingLineCompleated,
        QuizPartCompleate,
        AcceptQuest,
        GetWeaponParts,
        ActivateShopUi,
        OnCharacterLogOut,
        LoadTrairMenu

    }

    public enum Seasons
    {
        Spring = 0,
        Summer,
        Fall,
        Winter
    }

    public enum ActiveAbilityAreas
    {
        TeleportField = 0,
        TickingDamage,
        Stun,
        Slow
    }


    public enum AdminPackersClient : int
    {
        ManageConversations = 0,
        GetNpcConversation
    }
    public enum AdminPackersServer : int
    {
        ManageConversations = 0,
        GetNpcConversation
    }

}