class ChatRoomRights
{
    Id int |  | NO
    RightName nvarchar |  | NO
    PojectId int |  | YES
    Background nvarchar |  | YES
    Foreground nvarchar |  | YES
}
class UserNotes
{
    Id int |  | NO
    NoteBackground nvarchar |  | NO
    NoteForeground nvarchar |  | NO
    Content nvarchar |  | YES
    DateOfMessage datetime |  | YES
    TopPos nvarchar |  | YES
    LeftPos nvarchar |  | YES
}
class AssociatedChatRoomRights
{
    Id int |  | NO
    ChatRoomId int |  | NO
    RightId int |  | NO
}
class AssociatedAccountNotes
{
    Id int |  | NO
    NoteId int |  | NO
    UserAccountId int |  | NO
    ProjectId int |  | NO
}
class AssociatedUserChatRights
{
    Id int |  | NO
    UserId int |  | YES
    RightId int |  | YES
    ProjectId int |  | YES
}
class PublicMessage
{
    Id int |  | NO
    Content nvarchar |  | NO
    WorkItemRelationid int |  | YES
    Rating int |  | YES
    Email nvarchar |  | NO
    DateOfMessage datetime |  | YES
}
class AssociatedProjectBoards
{
    Id int |  | NO
    BoardId int |  | YES
    ProjectId int |  | YES
    Position int |  | YES
}
class AssociatedProjectPublicMessages
{
    Id int |  | NO
    MessageId int |  | NO
    ProjectId int |  | NO
}
class Documentation
{
    Id int |  | NO
    ProjectId int |  | YES
}
class Notifications
{
    Id int |  | NO
    Content nvarchar |  | NO
    WorkItemRelationid int |  | YES
    DateOfMessage datetime |  | YES
    NotificationType int |  | YES
}
class DocumentationCategory
{
    Id int |  | NO
    CategoryName nvarchar |  | YES
    DocumentationId int |  | YES
}
class NotificationTypes
{
    Id int |  | NO
    NotificationType nvarchar |  | NO
    Icon nvarchar |  | YES
}
class Risks
{
    Id int |  | NO
    RiskName nvarchar |  | YES
}
class DocumentationCategoryField
{
    Id int |  | NO
    PageName nvarchar |  | YES
    CategoryId int |  | YES
}
class AssociatedProjectNotifications
{
    Id int |  | NO
    NotificationId int |  | NO
    ProjectId int |  | NO
    NewNotification int |  | YES
    UserAccountId int |  | YES
    IsRead int |  | YES
}
class AssociatedDocumentationCategoryPage
{
    Id int |  | NO
    Content nvarchar |  | YES
    CategoryField int |  | YES
    Title nvarchar |  | YES
}
class Efforts
{
    Id int |  | NO
    EffortName nvarchar |  | YES
}
class AssociatedUserNotifications
{
    Id int |  | NO
    NotificationId int |  | NO
    UserId int |  | NO
    NewNotification int |  | YES
    IsRead int |  | YES
}
class ValueAreas
{
    Id int |  | NO
    ValueAreaName nvarchar |  | YES
}
class AssociatedWrorkItemChildren
{
    Id int |  | NO
    WorkItemId int |  | YES
    WorkItemChildId int |  | YES
    RelationType int |  | YES
}
class AssociatedChatPersonalMessages
{
    Id int |  | NO
    ProjectId int |  | YES
    PublicMessageId int |  | YES
    SenderId int |  | YES
    ReciverId int |  | YES
}
class PublicMessages
{
    Id int |  | NO
    SenderName nvarchar |  | NO
    MessageContent nvarchar |  | YES
    DateOfMessage datetime |  | YES
    IsNew int |  | YES
    SenderId int |  | YES
}
class NotificationRights
{
    Id int |  | NO
    PersonalMessageNEnabled int |  | YES
    ChatChannelNEnabled int |  | YES
    UpdateWorkItemNEnabled int |  | YES
    CreateWorkItemNEnabled int |  | YES
    PublicDiscussionMNEnabled int |  | YES
    FeedbackNEnabled int |  | YES
    BugReportNEnabled int |  | YES
    ChanegelogNEnabled int |  | YES
}
class AssociatedAccountProjectNotificationRights
{
    Id int |  | NO
    ProjectId int |  | YES
    UserId int |  | YES
    RightId int |  | YES
}
class AssociatedProjectPublicDiscussions
{
    Id int |  | NO
    ProjectId int |  | YES
    PublicMessageId int |  | YES
}
class Commits
{
    Id int |  | NO
    CommitData nvarchar |  | NO
    DateOfCommit datetime |  | YES
    CommitedBy nvarchar |  | YES
    CommitKey nvarchar |  | YES
}
class Branches
{
    Id int |  | NO
    ProjectId int |  | NO
    DateOfCreation datetime |  | YES
    BranchName nvarchar |  | YES
}
class UserDashboards
{
    Id int |  | NO
    DashboardName nvarchar |  | YES
    UserId int |  | YES
    DateOfDashboard datetime |  | YES
    ProjectId int |  | YES
    TeamDashboard int |  | YES
}
class SystemFiles
{
    Id int |  | NO
    SenderName nvarchar |  | NO
    FileLocation nvarchar |  | YES
    DateOfMessage datetime |  | YES
    FileType int |  | YES
}
class AssociatedBranchCommits
{
    Id int |  | NO
    CommitId int |  | NO
    BranchId int |  | NO
}
class UserDashboardItem
{
    Id int |  | NO
    ItemName nvarchar |  | YES
    DataRow int |  | YES
    DataCol int |  | YES
    DataSizeY int |  | YES
    DataSizeX int |  | YES
    UserDashboard int |  | YES
}
class AssociatedWorkItemFiles
{
    Id int |  | NO
    WorkItemId int |  | YES
    FileId int |  | YES
}
class WorkItemRealtionshipType
{
    Id int |  | NO
    Name nvarchar |  | NO
}
class UserDashboardItemComponent
{
    Id int |  | NO
    ComponentName nvarchar |  | YES
    IsRow int |  | YES
    ColumnNumber int |  | YES
    ComponentInternalName nvarchar |  | YES
}
class AssociatedUserDashboardItemComponent
{
    Id int |  | NO
    Item int |  | YES
    ItemComponent int |  | YES
}
class AssociatedProjectFeedback
{
    Id int |  | NO
    ProjectId int |  | YES
    MessageId int |  | YES
    rating int |  | YES
}
class UserAccounts
{
    Id int |  | NO
    Password nvarchar |  | NO
    CreationDate datetime |  | NO
    Email nvarchar |  | YES
    FirstName nvarchar |  | YES
    LastName nvarchar |  | YES
    ProjectRights int |  | YES
    GitUsername nvarchar |  | YES
    Salt nvarchar |  | YES
    TeamId int |  | YES
}
class AssociatedRepositoryBranches
{
    Id int |  | NO
    RepositoryId int |  | NO
    BranchId int |  | NO
}
class ApiKeys
{
    Id int |  | NO
    FeatureName nvarchar |  | YES
    SecretKey nvarchar |  | YES
}
class WorkItemTypes
{
    Id int |  | NO
    TypeName nvarchar |  | YES
    Icon nvarchar |  | YES
}
class AssociatedProjectApiKeys
{
    Id int |  | NO
    ProjectId int |  | YES
    KeyId int |  | YES
    ApiSecret nvarchar |  | YES
}
class WorkItem
{
    Id int |  | NO
    WorkItemTypeId int |  | YES
    Title nvarchar |  | YES
    AssignedAccount int |  | YES
    StateId int |  | YES
    AreaId int |  | YES
    Description nvarchar |  | YES
    StartDate datetime |  | YES
    EndDate datetime |  | YES
    PriorityId int |  | YES
    ClassificationId int |  | YES
    DevelopmentId int |  | YES
    ParentId int |  | YES
    Reason int |  | YES
    Iteration int |  | YES
    RepoSteps nvarchar |  | YES
    SystemInfo nvarchar |  | YES
    ResolvedReason nvarchar |  | YES
    itemPriority int |  | YES
    Severity int |  | YES
    Activity int |  | YES
    OriginEstitame nvarchar |  | YES
    Remaining nvarchar |  | YES
    Compleated nvarchar |  | YES
    BranchId int |  | YES
    FoundInBuild int |  | YES
    IntegratedInBuild int |  | YES
    ReasonId int |  | YES
    RelationId int |  | YES
    RiskId int |  | YES
    BusinessValue nvarchar |  | YES
    TimeCapacity nvarchar |  | YES
    ValueAreaId int |  | YES
    Effort nvarchar |  | YES
    StackRank nvarchar |  | YES
    DueDate datetime |  | YES
    StoryPoints nvarchar |  | YES
    AcceptanceCriteria nvarchar |  | YES
    IsPublic int |  | YES
}
class Projects
{
    Id int |  | NO
    RepositoryId int |  | NO
    ProjectName nvarchar |  | YES
    ProjectDescription nvarchar |  | YES
    ProjectTitle nvarchar |  | YES
    CreationDate datetime |  | YES
    BoardId int |  | YES
    PublicBoard int |  | YES
    AllowPublicControl int |  | YES
    AllowPublicFeatures int |  | YES
    AllowPublicBugs int |  | YES
    AllowPublicFeedback int |  | YES
    AllowPublicMessages int |  | YES
    ImageLocation nvarchar |  | YES
}
class FileTypes
{
    Id int |  | NO
    TypeName nvarchar |  | YES
}
class sysdiagrams
{
    name nvarchar |  | NO
    principal_id int |  | NO
    diagram_id int |  | NO
    version int |  | YES
    definition varbinary |  | YES
}
class Repository
{
    Id int |  | NO
    FolderPath nvarchar |  | NO
}
class ChatChannelTypes
{
    Id int |  | NO
    TypeName nvarchar |  | YES
}
class ChatChannels
{
    Id int |  | NO
    ChannelName nvarchar |  | YES
    ChannelType int |  | YES
    ChatRoom int |  | YES
}
class Files
{
    Id int |  | NO
    FilePath nvarchar |  | YES
    CurrentName nvarchar |  | YES
    FileData nvarchar |  | YES
    DateOfFile datetime |  | YES
}
class AssociatedChatChannelMessages
{
    Id int |  | NO
    PublicMessageId int |  | YES
    ChatChannelId int |  | YES
}
class AssociatedProjectIterations
{
    Id int |  | NO
    ProjectId int |  | NO
    IterationId int |  | NO
    ActiveIteration int |  | YES
}
class AssociatedCommitFiles
{
    Id int |  | NO
    FileId int |  | YES
    CommitId int |  | YES
    DateOfCommit datetime |  | YES
}
class UserQueries
{
    Id int |  | NO
    QueryName nvarchar |  | YES
    UserId int |  | YES
    QueryData nvarchar |  | YES
    DateOfQuery datetime |  | YES
    IsShared int |  | YES
    ProjectId int |  | YES
}
class Boards
{
    Id int |  | NO
    RepositoryId int |  | NO
    BoardType int |  | NO
    BoardName nvarchar |  | YES
}
class UserRights
{
    Id int |  | NO
    WorkItemRule smallint |  | NO
    ChatChannelsRule smallint |  | NO
    UpdateUserRights smallint |  | NO
    ManageIterations smallint |  | NO
    ManageUserdays smallint |  | NO
    ViewOtherPeoplesWork smallint |  | NO
    Documentation int |  | YES
}
class AssociatedBoardWorkItems
{
    Id int |  | NO
    BoardId int |  | NO
    WorkItemId int |  | NO
    ProjectId int |  | YES
}
class AssociatedProjectMemberRights
{
    Id int |  | NO
    RightsId int |  | YES
    UserAccountId int |  | YES
    ProjectId int |  | YES
}
class ChatRooms
{
    Id int |  | NO
    RoomName nvarchar |  | YES
    ProjectId int |  | YES
}
class AssociatedProjectMembers
{
    Id int |  | NO
    UserAccountId int |  | NO
    ProjectId int |  | NO
    RepositoryId int |  | NO
}
class WorkItemStates
{
    Id int |  | NO
    StateName nvarchar |  | YES
}
class WorkItemAreas
{
    ID int |  | NO
    AreaName nvarchar |  | NO
}
class Teams
{
    Id int |  | NO
    TeamName nvarchar |  | YES
    ProjectId int |  | YES
    DateOfCreation datetime |  | YES
}
class TeamDashboards
{
    Id int |  | NO
    DashboardName nvarchar |  | YES
    TeamId int |  | YES
    DateOfCreation datetime |  | YES
}
class PremadeWidgets
{
    Id int |  | NO
    ControlName nvarchar |  | YES
    ViewComponentName nvarchar |  | YES
    ControlDescription nvarchar |  | YES
    Settings nvarchar |  | YES
    CustomSettings int |  | YES
}
class AssociatedUserDashboardPremade
{
    Id int |  | NO
    UserDashboard int |  | YES
    PremadeWidgetId int |  | YES
    DataRow int |  | YES
    DataCol int |  | YES
    DataSizeX int |  | YES
    DataSizeY int |  | YES
    CustomSettings nvarchar |  | YES
}
class Changelogs
{
    Id int |  | NO
    LogDetails varchar |  | NO
    DayOfLog int |  | YES
}
class AssociatedProjectChangelogs
{
    Id int |  | NO
    LogId int |  | YES
    ProjectId int |  | YES
    CurrentMonth int |  | YES
    LogYear int |  | YES
}
class WorkItemPriorities
{
    Id int |  | NO
    PriorityName nvarchar |  | NO
}
class AssociatedUserChatNotifications
{
    Id int |  | NO
    UserId int |  | YES
    ProjectId int |  | YES
    ChatChannelId int |  | YES
}
class WorkItemSeverities
{
    Id int |  | NO
    SeverityName nvarchar |  | NO
}
class AssociatedWorkItemChangelogs
{
    Id int |  | NO
    LogId int |  | YES
    workitemId int |  | YES
    ProjectId int |  | YES
}
class WorkItemActivity
{
    Id int |  | NO
    ActivityName nvarchar |  | NO
}
class Surveys
{
    Id int |  | NO
    SurveyTitle nvarchar |  | YES
    SurveyLogo nvarchar |  | YES
    SurveyDescription nvarchar |  | YES
    Email nvarchar |  | YES
    ProjectId int |  | YES
    CreatedBy int |  | YES
    CreatedAt datetime |  | YES
}
class WorkItemIterations
{
    Id int |  | NO
    IterationName nvarchar |  | NO
    IsActive int |  | YES
}
class SurveyPage
{
    Id int |  | NO
    PageName nvarchar |  | YES
    SurveyId int |  | YES
}
class WorkItemReasons
{
    Id int |  | NO
    ReasonName nvarchar |  | NO
}
class SurveyComponent
{
    Id int |  | NO
    ComponentInternalName nvarchar |  | YES
    PlatformName nvarchar |  | YES
}
class AssociatedPageSurveyComponents
{
    Id int |  | NO
    ComponentId int |  | YES
    PageId int |  | YES
    DataSource nvarchar |  | YES
    Question nvarchar |  | YES
}
class Builds
{
    Id int |  | NO
    ReasonName nvarchar |  | NO
    FrameworkVersion int |  | YES
    DateOfBuild datetime |  | YES
    CompleationStatus int |  | YES
    AccountId int |  | YES
    PlatformId int |  | YES
}
class WorkItemMessage
{
    Id int |  | NO
    SenderId int |  | NO
    Content nvarchar |  | YES
    DateOfMessage datetime |  | YES
}
class AssociatedProjectBuilds
{
    Id int |  | NO
    RepositoryId int |  | YES
    BuildId int |  | YES
    ProjectId int |  | YES
}
class AssociatedWorkItemMessages
{
    Id int |  | NO
    WorkItemId int |  | NO
    MessageId int |  | NO
}
class WorkItemRelations
{
    Id int |  | NO
    RelationName nvarchar |  | YES
}
AssociatedAccountNotes "1" *-- "many" UserNotes
AssociatedAccountNotes "1" *-- "many" UserAccounts
AssociatedAccountNotes "1" *-- "many" Projects
AssociatedAccountProjectNotificationRights "1" *-- "many" Projects
AssociatedAccountProjectNotificationRights "1" *-- "many" UserAccounts
AssociatedAccountProjectNotificationRights "1" *-- "many" NotificationRights
AssociatedBoardWorkItems "1" *-- "many" Boards
AssociatedBoardWorkItems "1" *-- "many" WorkItem
AssociatedBoardWorkItems "1" *-- "many" Projects
AssociatedBranchCommits "1" *-- "many" Commits
AssociatedBranchCommits "1" *-- "many" Branches
AssociatedChatChannelMessages "1" *-- "many" PublicMessages
AssociatedChatChannelMessages "1" *-- "many" ChatChannels
AssociatedChatPersonalMessages "1" *-- "many" Projects
AssociatedChatPersonalMessages "1" *-- "many" PublicMessages
AssociatedChatPersonalMessages "1" *-- "many" UserAccounts
AssociatedChatPersonalMessages "1" *-- "many" UserAccounts
AssociatedChatRoomRights "1" *-- "many" ChatRooms
AssociatedChatRoomRights "1" *-- "many" ChatRoomRights
AssociatedCommitFiles "1" *-- "many" Files
AssociatedCommitFiles "1" *-- "many" Commits
AssociatedDocumentationCategoryPage "1" *-- "many" DocumentationCategoryField
AssociatedPageSurveyComponents "1" *-- "many" SurveyComponent
AssociatedPageSurveyComponents "1" *-- "many" SurveyPage
AssociatedProjectApiKeys "1" *-- "many" Projects
AssociatedProjectApiKeys "1" *-- "many" ApiKeys
AssociatedProjectBoards "1" *-- "many" Boards
AssociatedProjectBoards "1" *-- "many" Projects
AssociatedProjectBuilds "1" *-- "many" Repository
AssociatedProjectBuilds "1" *-- "many" Builds
AssociatedProjectBuilds "1" *-- "many" Projects
AssociatedProjectChangelogs "1" *-- "many" Changelogs
AssociatedProjectChangelogs "1" *-- "many" Projects
AssociatedProjectFeedback "1" *-- "many" Projects
AssociatedProjectFeedback "1" *-- "many" PublicMessages
AssociatedProjectIterations "1" *-- "many" Projects
AssociatedProjectIterations "1" *-- "many" WorkItemIterations
AssociatedProjectMemberRights "1" *-- "many" UserRights
AssociatedProjectMemberRights "1" *-- "many" UserAccounts
AssociatedProjectMemberRights "1" *-- "many" Projects
AssociatedProjectMembers "1" *-- "many" UserAccounts
AssociatedProjectMembers "1" *-- "many" Projects
AssociatedProjectMembers "1" *-- "many" Repository
AssociatedProjectNotifications "1" *-- "many" Notifications
AssociatedProjectNotifications "1" *-- "many" Projects
AssociatedProjectNotifications "1" *-- "many" UserAccounts
AssociatedProjectPublicDiscussions "1" *-- "many" Projects
AssociatedProjectPublicDiscussions "1" *-- "many" PublicMessages
AssociatedProjectPublicMessages "1" *-- "many" PublicMessage
AssociatedProjectPublicMessages "1" *-- "many" Projects
AssociatedRepositoryBranches "1" *-- "many" Repository
AssociatedRepositoryBranches "1" *-- "many" Branches
AssociatedUserChatNotifications "1" *-- "many" UserAccounts
AssociatedUserChatNotifications "1" *-- "many" Projects
AssociatedUserChatNotifications "1" *-- "many" ChatChannels
AssociatedUserChatRights "1" *-- "many" UserAccounts
AssociatedUserChatRights "1" *-- "many" ChatRoomRights
AssociatedUserChatRights "1" *-- "many" Projects
AssociatedUserDashboardItemComponent "1" *-- "many" UserDashboardItem
AssociatedUserDashboardItemComponent "1" *-- "many" UserDashboardItemComponent
AssociatedUserDashboardPremade "1" *-- "many" UserDashboards
AssociatedUserDashboardPremade "1" *-- "many" PremadeWidgets
AssociatedUserNotifications "1" *-- "many" Notifications
AssociatedUserNotifications "1" *-- "many" UserAccounts
AssociatedWorkItemChangelogs "1" *-- "many" Changelogs
AssociatedWorkItemChangelogs "1" *-- "many" WorkItem
AssociatedWorkItemChangelogs "1" *-- "many" Projects
AssociatedWorkItemFiles "1" *-- "many" WorkItem
AssociatedWorkItemFiles "1" *-- "many" SystemFiles
AssociatedWorkItemMessages "1" *-- "many" WorkItem
AssociatedWorkItemMessages "1" *-- "many" WorkItemMessage
AssociatedWrorkItemChildren "1" *-- "many" WorkItem
AssociatedWrorkItemChildren "1" *-- "many" WorkItem
AssociatedWrorkItemChildren "1" *-- "many" WorkItemTypes
Branches "1" *-- "many" Projects
ChatChannels "1" *-- "many" ChatChannelTypes
ChatChannels "1" *-- "many" ChatRooms
ChatRoomRights "1" *-- "many" Projects
ChatRooms "1" *-- "many" Projects
Documentation "1" *-- "many" Projects
DocumentationCategory "1" *-- "many" Documentation
DocumentationCategoryField "1" *-- "many" DocumentationCategory
Notifications "1" *-- "many" NotificationTypes
Projects "1" *-- "many" Repository
SurveyPage "1" *-- "many" Surveys
Surveys "1" *-- "many" Projects
Surveys "1" *-- "many" UserAccounts
SystemFiles "1" *-- "many" FileTypes
TeamDashboards "1" *-- "many" Teams
UserDashboardItem "1" *-- "many" UserDashboards
UserDashboards "1" *-- "many" Projects
UserDashboards "1" *-- "many" TeamDashboards
UserQueries "1" *-- "many" UserAccounts
WorkItem "1" *-- "many" WorkItemTypes
WorkItem "1" *-- "many" UserAccounts
WorkItem "1" *-- "many" WorkItemStates
WorkItem "1" *-- "many" WorkItemAreas
WorkItem "1" *-- "many" WorkItemPriorities
WorkItem "1" *-- "many" WorkItemIterations
WorkItem "1" *-- "many" WorkItemSeverities
WorkItem "1" *-- "many" WorkItemActivity
WorkItem "1" *-- "many" WorkItemReasons
WorkItem "1" *-- "many" WorkItemRelations
WorkItem "1" *-- "many" Risks
WorkItem "1" *-- "many" ValueAreas
WorkItemMessage "1" *-- "many" UserAccounts