// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Rokono_Control.Models
{
    public partial class AssociatedWorkItemTags
    {
        public int Id { get; set; }
        public int? WorkItemId { get; set; }
        public int? TagId { get; set; }
        public int? CreatedAt { get; set; }
        public int? UpdatedAt { get; set; }

        public virtual Tags Tag { get; set; }
        public virtual WorkItem WorkItem { get; set; }
    }
}