// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Rokono_Control.Models
{
    public partial class AssociatedChatRoomRights
    {
        public int Id { get; set; }
        public int ChatRoomId { get; set; }
        public int RightId { get; set; }

        public virtual ChatRooms ChatRoom { get; set; }
        public virtual ChatRoomRights Right { get; set; }
    }
}