// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Rokono_Control.Models
{
    public partial class AssociatedProjectChangelogs
    {
        public int Id { get; set; }
        public int? LogId { get; set; }
        public int? ProjectId { get; set; }
        public int? CurrentMonth { get; set; }
        public int? LogYear { get; set; }

        public virtual Changelogs Log { get; set; }
        public virtual Projects Project { get; set; }
    }
}