// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Rokono_Control.Models
{
    public partial class AssociatedBlogPosts
    {
        public int Id { get; set; }
        public int? BlogPostId { get; set; }
        public int? RelatedPostId { get; set; }
        public int? DateOfRelation { get; set; }

        public virtual BlogPosts BlogPost { get; set; }
        public virtual BlogPosts RelatedPost { get; set; }
    }
}