// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Rokono_Control.Models
{
    public partial class AssociatedProjectPublicMessages
    {
        public int Id { get; set; }
        public int MessageId { get; set; }
        public int ProjectId { get; set; }

        public virtual PublicMessage Message { get; set; }
        public virtual Projects Project { get; set; }
    }
}