// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Rokono_Control.Models
{
    public partial class BlogPosts
    {
        public BlogPosts()
        {
            AssociatedBlogPostsBlogPost = new HashSet<AssociatedBlogPosts>();
            AssociatedBlogPostsRelatedPost = new HashSet<AssociatedBlogPosts>();
        }

        public int Id { get; set; }
        public int? DateOfPost { get; set; }
        public string PostContent { get; set; }
        public int? Category { get; set; }
        public string Facebook { get; set; }
        public string Instagram { get; set; }
        public string Linkdin { get; set; }
        public int? ProjectId { get; set; }

        public virtual BlogPostCategories CategoryNavigation { get; set; }
        public virtual Projects Project { get; set; }
        public virtual ICollection<AssociatedBlogPosts> AssociatedBlogPostsBlogPost { get; set; }
        public virtual ICollection<AssociatedBlogPosts> AssociatedBlogPostsRelatedPost { get; set; }
    }
}