// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Rokono_Control.Models
{
    public partial class BlogPostCategories
    {
        public BlogPostCategories()
        {
            BlogPosts = new HashSet<BlogPosts>();
        }

        public int Id { get; set; }
        public string CategoryName { get; set; }
        public int? ProjectId { get; set; }

        public virtual Projects Project { get; set; }
        public virtual ICollection<BlogPosts> BlogPosts { get; set; }
    }
}