// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Rokono_Control.Models
{
    public partial class Efforts
    {
        public int Id { get; set; }
        public string EffortName { get; set; }
    }
}