// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Rokono_Control.Models
{
    public partial class Layouts
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int? CreatedAt { get; set; }
        public int? UpdatedAt { get; set; }
        public int? Owner { get; set; }
        public string LayoutThumnail { get; set; }
        public int? ProjectId { get; set; }
        public int? WorkItemId { get; set; }
        public string WorkItemResult { get; set; }

        public virtual Projects Project { get; set; }
        public virtual WorkItem WorkItem { get; set; }
    }
}