// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Rokono_Control.Models
{
    public partial class WorkItemTypes
    {
        public WorkItemTypes()
        {
            AssociatedWrorkItemChildren = new HashSet<AssociatedWrorkItemChildren>();
            WorkItem = new HashSet<WorkItem>();
        }

        public int Id { get; set; }
        public string TypeName { get; set; }
        public string Icon { get; set; }

        public virtual ICollection<AssociatedWrorkItemChildren> AssociatedWrorkItemChildren { get; set; }
        public virtual ICollection<WorkItem> WorkItem { get; set; }
    }
}